---
# Site
baseurl: "https://hugo-blaupause.netlify.com/"
title: "jiulog-hugo"
enableRobotsTXT: true
googleAnalytics: ""
# Content
languageCode: "ko-kr"
defaultContentLanguage: "ko"
# Formats
metaDataFormat: "yaml"
# -----------------------------
# DO NOT CHANGE BELOW THIS LINE
# -----------------------------
disableLiveReload: true
watch: false
---
